baseURL = 'https://franciscomarrero.dev/'
defaultContentLanguage = 'en'
# Automatically generate robots.txt
enableEmoji = true
enableRobotsTXT = true
locale = 'en'
theme = 'custom'
title = 'Francisco Marrero'

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 1
  [[menus.main]]
    # Display name
    name = 'Projects'
    pageRef = '/projects/'
    weight = 2
    
  [[menus.main]]
    name='About Me'
    pageRef = '/about-me'
    weight = 5
  [[menus.main]]
    name = 'Github'
    url = 'https://github.com/marrero171'
    weight = 6
    # Surround the menu entry (or name) with HTML content, such as Feather
    # icons: https://feathericons.com
  [[menus.main]]
    name = 'Linkedin'
    url = 'https://www.linkedin.com/in/francisco-marrero-a09358207/'
    weight = 6

[params]
  # Choose the color shown when hyperlinks are hovered over
  # accentColor = '#FF4D4D'
  accentColor = '#32CD32'

  # Inject arbitrary HTML via the <head> tag
  # Best used for importing custom JavaScript, CSS, or analytics
  customHeadHTML = "<script defer src='https://cloud.umami.is/script.js' data-website-id='2e7a9092-f7a8-4e76-8fb3-c0038ab2e6b0'></script>"

  # Configure how post dates are displayed
  # dateFormat must be set if lastmod is declared in front matter, or
  # enableGitInfo is true
  dateFormat = 'January 2, 2006'
  
  # Home page meta description
  description = 'Fullstack Web Developer, Game Programmer'

    socialIcons = [
    {name = 'itchdotio', url = 'https://marrero171.itch.io/'},
    {name = 'github', url = 'https://github.com/marrero171'},
    {name = 'linkedin', url = 'https://www.linkedin.com/in/francisco-marrero-a09358207/'},
    {name = 'email', url = 'mailto:francisco@franciscomarrero.dev'},
  ]



  # Footer text (i.e. author/project name)
  footer = 'Francisco Marrero'

  # Define SEO keywords
  metaKeywords = ['portfolio', 'about me', 'resume']

[caches]
  [caches.images]
    dir = ':cacheDir/images'
